version: '3.8'

x-xxx-common-services-config: &common-services-config
  restart: always

x-mongo-secrets: &mongo-credentials
  MONGO_USER: &mongo-user root
  MONGO_PASS: &mongo-pass toor
  MONGO_AUTH_DB: admin
  MONGO_HOST: mongo
  MONGO_PORT: 27017
  MONGO_DB_NAME: orderdb

x-kafka-env: &kafka-env
  KAFKA_BROKER_ID: 1
  KAFKA_ADVERTISED_PORT: 9092
  BROKER_ID_COMMAND: "hostname | cut -d'-' -f2"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_CREATE_TOPICS: "logging:20:1,pushnotifications:10:1,invoicing:10:1,mailing:10:1,userupdates:10:1,orderupdates:10:1"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"

services:
  mongo:
    <<: *common-services-config
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: *mongo-user
      MONGO_INITDB_ROOT_PASSWORD: *mongo-pass
    ports:
      - 27017:27017
    volumes:
      - mongo-db-data:/data/db

  payment_manager:
    <<: *common-services-config
    build: ../payment_manager
    environment: *mongo-credentials
    ports:
      - 5555:5555
    volumes:
      - ../payment_manager:/app

  zookeeper:
    <<: *common-services-config
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_MY_ID: 1

  kafka:
    <<: *common-services-config
    image: wurstmeister/kafka
    environment: *kafka-env

volumes:
  mongo-db-data:
