version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb-payment"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: calabretta-mauro/payment-mongodb
    ports:
      - 8080:8080
    links:
      - mongodb



