version: "3"



x-mongo-secrets: &mongo-credentials
  MONGO_USER: &mongo-user root
  MONGO_PASS: &mongo-pass toor
  MONGO_AUTH_DB: admin
  MONGO_HOST: mongo
  MONGO_PORT: 27017
  MONGO_DB_NAME: mongo-payment-DB

x-common-settings: &common-settings
  restart: always
services:
  mongo:
    image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: *mongo-user
        MONGO_INITDB_ROOT_PASSWORD: *mongo-pass
      port:
        - 27017:27017
      volume:
        mongo-db-data:/data/db

  payment-manager:
    <<: *common-settings
    build: ../path da definire MINUTO 1.09.32
    environment: *mongo-credentials
    port:
      - 8088:8088
    volumes:
      - ../sempre roba del path MINUTO 1.10.32

volumes:
  mongo-db-data:


#services:
  #mongodb:
  #image: mongo:4.2.2
    #container_name: "mongodb-payment"
    #ports:
    #- 27017:27017

  #app:
    #image: calabretta-mauro/payment-mongodb
    #ports:
      #- 8080:8080
    #links:
      #- mongodb

