version: "3"
services:
  mongodb:
    image: mongo:4.2.2
    container_name: "mongodb-payment"
    ports:
      - 27017:27017

  app:
    image: calabretta-mauro/payment-mongodb
    ports:
      - 8080:8080
    links:
      - mongodb



