apiVersion: v1
kind: Service
metadata:
  name: micropayment-service
  namespace: dsbd
spec:
  selector:
    app: micropayment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      name: micropayment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropayment-deploy
  namespace: dsbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micropayment
  template:
    metadata:
      labels:
        app: micropayment
    spec:
      containers:
        - name: micropayment-container
          image: ziocal/micropayment:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: MONGO_HOST
              value: paymentdb
            - name: MONGO_USER
              value: root
            - name: MONGO_PASS
              value: toor
            - name: MONGO_AUTH_DB
              value: admin
            - name: MONGO_DB_NAME
              value: paymentdb
            - name: MONGO_PORT
              value: "27017"


#  MONGO_USER: &mongo-user root
#  MONGO_PASS: &mongo-pass toor
#  MONGO_AUTH_DB: admin
#  MONGO_HOST: mongo
#  MONGO_PORT: 27017
#  MONGO_DB_NAME: orderdb
#            - name: token_secret
#              value: metro
#            - name: mongo_connection
#              value: mongodb://paymentdb:27017/
#            - name: mongo_user
#              value: DS
#            - name: mongo_pwd
#              value: "2023"
#            - name: minio_bucket
#              value: post
#            - name: minio_user
#              value: username
#            - name: minio_pwd
#              value: password
#            - name: minio_endpoint
#              value: "minio-service:9000"
#            - name: kafka_endpoint
#              value: "kafka:9092"

#          command: ["flask", "--app", "microPhoto", "run", "--host=0.0.0.0"]