apiVersion: v1
kind: Service
metadata:
  name: micropayment-svc
  namespace: dsbd
spec:
  selector:
    app: micropayment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      name: micropayment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropayment-deploy
  namespace: dsbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micropayment
  template:
    metadata:
      labels:
        app: micropayment
    spec:
      containers:
        - name: micropayment-container
          image: ziocal/micropayment:4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: MONGO_HOST
              value: paymentdb-svc
            - name: MONGO_USER
              value: root
            - name: MONGO_PASS
              value: toor
            - name: MONGO_AUTH_DB
              value: admin
            - name: MONGO_DB_NAME
              value: paymentdb
            - name: MONGO_PORT
              value: "27017"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_ORDERS_TOPIC
              value: "orders"
            - name: KAFKA_ERROR_TOPIC
              value: "logging"