
kafkaServer:
  - kafka.dsbd.svc.cluster.local:9092
#  - kafka.dsbd:9092
env:
  - name: KAFKA_SERVER
    value: "kafka.dsbd.svc.cluster.local:9092"
  - name: LOG_LEVEL
    value: "debug"
prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    apiVersion: "monitoring.coreos.com/v1"
    interval: "30s"
    scrapeTimeout: 10s
    selector:
      matchLabels:
        app: kafka-exporter
    # If serviceMonitor is enabled and you want prometheus to automatically register
    # target using serviceMonitor, add additionalLabels with prometheus release name
    # e.g. If you have deployed kube-prometheus-stack with release name kube-prometheus
    # then additionalLabels will be
    # additionalLabels:
    #   release: kube-prometheus
    additionalLabels: 
      release: prometheus
    
